In [12]:
import numpy as np
import keras
from keras.layers import Dense, Input, Activation
from keras.models import Sequential
from keras.optimizers import SGD

In [ ]:
# One-hot encoding


In [157]:
x = np.array([
        [0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]
       ])
y = np.array([[1., 0.], [0., 1.], [0., 1.], [1., 0.]])
y = np.array([[0.], [1.], [1.], [0.]])

In [165]:
y = np.array([0., 0., 1., 1])

In [166]:
y.reshape(-1, 1)

array([[0.],
       [0.],
       [1.],
       [1.]])

In [158]:
x.shap

(4, 2)

In [161]:
model = Sequential()
model.add(Dense(4, input_dim=2))
model.add(Activation('relu'))
model.add(Dense(1))
model.add(Activation('relu'))

In [153]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_60 (Dense)             (None, 4)                 12        
_________________________________________________________________
activation_59 (Activation)   (None, 4)                 0         
_________________________________________________________________
dense_61 (Dense)             (None, 2)                 10        
_________________________________________________________________
activation_60 (Activation)   (None, 2)                 0         
Total params: 22
Trainable params: 22
Non-trainable params: 0
_________________________________________________________________


In [162]:
model.compile(optimizer=SGD(lr=0.1, momentum=0.5), loss='binary_crossentropy', metrics=['accuracy'])

In [163]:
model.fit(x, y, verbose=1, epochs=1000, batch_size=None)

Epoch 1/1000
4/4 [==============================] - 0s 113ms/step - loss: 4.1035 - acc: 0.7500
Epoch 2/1000
4/4 [==============================] - 0s 700us/step - loss: 1.2017 - acc: 0.7500
Epoch 3/1000
4/4 [==============================] - 0s 664us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 4/1000
4/4 [==============================] - 0s 927us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 5/1000
4/4 [==============================] - 0s 765us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 6/1000
4/4 [==============================] - 0s 1ms/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 7/1000
4/4 [==============================] - 0s 693us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 8/1000
4/4 [==============================] - 0s 656us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 9/1000
4/4 [==============================] - 0s 721us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 10/1000
4/4 [==============================] - 0s 914us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 11/1000
4/4 [

Epoch 84/1000
4/4 [==============================] - 0s 650us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 85/1000
4/4 [==============================] - 0s 595us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 86/1000
4/4 [==============================] - 0s 1ms/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 87/1000
4/4 [==============================] - 0s 566us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 88/1000
4/4 [==============================] - 0s 560us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 89/1000
4/4 [==============================] - 0s 594us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 90/1000
4/4 [==============================] - 0s 1ms/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 91/1000
4/4 [==============================] - 0s 625us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 92/1000
4/4 [==============================] - 0s 877us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 93/1000
4/4 [==============================] - 0s 679us/step - loss: 7.9712 - acc: 0.0000e+00
Epoc

Epoch 166/1000
4/4 [==============================] - 0s 757us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 167/1000
4/4 [==============================] - 0s 1ms/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 168/1000
4/4 [==============================] - 0s 582us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 169/1000
4/4 [==============================] - 0s 924us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 170/1000
4/4 [==============================] - 0s 746us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 171/1000
4/4 [==============================] - 0s 866us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 172/1000
4/4 [==============================] - 0s 717us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 173/1000
4/4 [==============================] - 0s 933us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 174/1000
4/4 [==============================] - 0s 829us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 175/1000
4/4 [==============================] - 0s 854us/step - loss: 7.9712 - acc: 0.0

Epoch 248/1000
4/4 [==============================] - 0s 824us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 249/1000
4/4 [==============================] - 0s 748us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 250/1000
4/4 [==============================] - 0s 2ms/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 251/1000
4/4 [==============================] - 0s 627us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 252/1000
4/4 [==============================] - 0s 2ms/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 253/1000
4/4 [==============================] - 0s 1ms/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 254/1000
4/4 [==============================] - 0s 754us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 255/1000
4/4 [==============================] - 0s 846us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 256/1000
4/4 [==============================] - 0s 767us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 257/1000
4/4 [==============================] - 0s 1ms/step - loss: 7.9712 - acc: 0.0000e+0

Epoch 330/1000
4/4 [==============================] - 0s 739us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 331/1000
4/4 [==============================] - 0s 700us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 332/1000
4/4 [==============================] - 0s 687us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 333/1000
4/4 [==============================] - 0s 845us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 334/1000
4/4 [==============================] - 0s 847us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 335/1000
4/4 [==============================] - 0s 777us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 336/1000
4/4 [==============================] - 0s 767us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 337/1000
4/4 [==============================] - 0s 755us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 338/1000
4/4 [==============================] - 0s 786us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 339/1000
4/4 [==============================] - 0s 761us/step - loss: 7.9712 - acc: 0

Epoch 412/1000
4/4 [==============================] - 0s 1ms/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 413/1000
4/4 [==============================] - 0s 774us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 414/1000
4/4 [==============================] - 0s 542us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 415/1000
4/4 [==============================] - 0s 703us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 416/1000
4/4 [==============================] - 0s 634us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 417/1000
4/4 [==============================] - 0s 794us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 418/1000
4/4 [==============================] - 0s 740us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 419/1000
4/4 [==============================] - 0s 597us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 420/1000
4/4 [==============================] - 0s 888us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 421/1000
4/4 [==============================] - 0s 936us/step - loss: 7.9712 - acc: 0.0

Epoch 494/1000
4/4 [==============================] - 0s 683us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 495/1000
4/4 [==============================] - 0s 565us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 496/1000
4/4 [==============================] - 0s 875us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 497/1000
4/4 [==============================] - 0s 626us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 498/1000
4/4 [==============================] - 0s 642us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 499/1000
4/4 [==============================] - 0s 585us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 500/1000
4/4 [==============================] - 0s 632us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 501/1000
4/4 [==============================] - 0s 622us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 502/1000
4/4 [==============================] - 0s 570us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 503/1000
4/4 [==============================] - 0s 579us/step - loss: 7.9712 - acc: 0

Epoch 576/1000
4/4 [==============================] - 0s 600us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 577/1000
4/4 [==============================] - 0s 577us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 578/1000
4/4 [==============================] - 0s 746us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 579/1000
4/4 [==============================] - 0s 1ms/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 580/1000
4/4 [==============================] - 0s 1ms/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 581/1000
4/4 [==============================] - 0s 694us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 582/1000
4/4 [==============================] - 0s 843us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 583/1000
4/4 [==============================] - 0s 1ms/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 584/1000
4/4 [==============================] - 0s 970us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 585/1000
4/4 [==============================] - 0s 548us/step - loss: 7.9712 - acc: 0.0000e

Epoch 658/1000
4/4 [==============================] - 0s 1ms/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 659/1000
4/4 [==============================] - 0s 764us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 660/1000
4/4 [==============================] - 0s 792us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 661/1000
4/4 [==============================] - 0s 570us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 662/1000
4/4 [==============================] - 0s 755us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 663/1000
4/4 [==============================] - 0s 721us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 664/1000
4/4 [==============================] - 0s 1ms/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 665/1000
4/4 [==============================] - 0s 768us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 666/1000
4/4 [==============================] - 0s 662us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 667/1000
4/4 [==============================] - 0s 546us/step - loss: 7.9712 - acc: 0.000

Epoch 740/1000
4/4 [==============================] - 0s 765us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 741/1000
4/4 [==============================] - 0s 1ms/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 742/1000
4/4 [==============================] - 0s 707us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 743/1000
4/4 [==============================] - 0s 726us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 744/1000
4/4 [==============================] - 0s 766us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 745/1000
4/4 [==============================] - 0s 841us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 746/1000
4/4 [==============================] - 0s 1ms/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 747/1000
4/4 [==============================] - 0s 1ms/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 748/1000
4/4 [==============================] - 0s 1ms/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 749/1000
4/4 [==============================] - 0s 684us/step - loss: 7.9712 - acc: 0.0000e+0

Epoch 822/1000
4/4 [==============================] - 0s 859us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 823/1000
4/4 [==============================] - 0s 865us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 824/1000
4/4 [==============================] - 0s 873us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 825/1000
4/4 [==============================] - 0s 938us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 826/1000
4/4 [==============================] - 0s 745us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 827/1000
4/4 [==============================] - 0s 760us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 828/1000
4/4 [==============================] - 0s 733us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 829/1000
4/4 [==============================] - 0s 904us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 830/1000
4/4 [==============================] - 0s 1ms/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 831/1000
4/4 [==============================] - 0s 713us/step - loss: 7.9712 - acc: 0.0

Epoch 904/1000
4/4 [==============================] - 0s 715us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 905/1000
4/4 [==============================] - 0s 668us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 906/1000
4/4 [==============================] - 0s 633us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 907/1000
4/4 [==============================] - 0s 681us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 908/1000
4/4 [==============================] - 0s 624us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 909/1000
4/4 [==============================] - 0s 855us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 910/1000
4/4 [==============================] - 0s 938us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 911/1000
4/4 [==============================] - 0s 609us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 912/1000
4/4 [==============================] - 0s 599us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 913/1000
4/4 [==============================] - 0s 604us/step - loss: 7.9712 - acc: 0

Epoch 986/1000
4/4 [==============================] - 0s 694us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 987/1000
4/4 [==============================] - 0s 946us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 988/1000
4/4 [==============================] - 0s 650us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 989/1000
4/4 [==============================] - 0s 635us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 990/1000
4/4 [==============================] - 0s 1ms/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 991/1000
4/4 [==============================] - 0s 1ms/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 992/1000
4/4 [==============================] - 0s 638us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 993/1000
4/4 [==============================] - 0s 665us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 994/1000
4/4 [==============================] - 0s 757us/step - loss: 7.9712 - acc: 0.0000e+00
Epoch 995/1000
4/4 [==============================] - 0s 709us/step - loss: 7.9712 - acc: 0.000

In [156]:
model.get_weights()

[array([[ 0.00956193, -1.8428439 , -1.5036525 ,  2.3181076 ],
        [-0.19622612,  1.8429725 ,  1.5032815 , -2.3189683 ]],
       dtype=float32),
 array([-3.9745413e-02, -2.4500361e-04,  1.6387494e-05, -2.5752670e-04],
       dtype=float32),
 array([[-0.29328185, -0.9466877 ],
        [-1.8226099 ,  1.8155966 ],
        [-1.7145102 ,  0.97344565],
        [-1.9085984 ,  2.728866  ]], dtype=float32),
 array([ 2.3700423, -2.370042 ], dtype=float32)]

In [164]:
model.predict(x)

array([[5.499943],
       [7.056371],
       [5.477809],
       [5.889635]], dtype=float32)